spring.application.name=policy
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel_vault
spring.datasource.username=postgres
spring.datasource.password=chathu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
sentinel.api.key=super-secret-vault-key-2026